### ISSUE TITLE
Add ISBN and wikidata ID per book in the corpus

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/novels-corpus#10]
We should try to add wikidata ID and IBAN per book.

Based on the libris ID this should probably be relatively easy to do by connecting to wikidata. For example via their REST API:
https://www.wikidata.org/wiki/Wikidata:Data_access
Add it as a separate column in the csv-file for the books.

Add a column in the metadata file called wikidata ID and add the wikidata id for the books that has a wikidata id.

**Comment by MansMeg** [comment]
@liamtabib It is always good if you close an issue with a short message so others can see what you have done to close it.

**Comment by liamtabib** [comment]
The wikidata ID has been retrieved for those books that have wikidata items registered, which is very few.
The ISBN of books were introduced after the period of publikation of the books, and therefore no isbn have been assigned to the books.

**Comment by MansMeg** [comment]
Great! Lets show this as a minidemo this friday.
