### ISSUE TITLE
Create a first version of an author database

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/novels-corpus#11]
Create two csv-files

authors.csv
with columns
person_id; name, gender, birthdate, deathdate, wikidata_id

for person_id setup a new uuid per author in the dataset.

and

written_by.csv
with columns
book_id; person_id

if there are multiple authors, just use multiple rows

book_id is probably easiest to use kbs dark... id.

This should be kind of straightforward if you get the wikidata IDs for each book.

**Comment by MansMeg** [comment]
Additional information:
- [ ] Extract the birth and deathyears from Libris so these can be used to identify the same authors
- [ ] Then create the csv files above with one row per unique author

**Comment by liamtabib** [comment]
The metadata has been constructed; the first version contains two files: authors.csv (author uuid, name or alias, birth/death) and written_by.csv (kb,libris,wiki ids, author uuid).
 
See corpus/Metadata for the csv's and scripts/Metdata scripts for the workflow.
