### ISSUE TITLE
Add uuid for each page in the corpus

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/novels-corpus#7]
We need to be able to efficiently identify pages in the corpus (for manual annotation)

Hence, we need to add an id per page with uuid. Look at the riksdagen corpus for an example how this is added.

@ninpnin which lib in Python do you use for this?

**Comment by ninpnin** [comment]
We have our own function in _pyriksdagen_ to generate UUIDs in the correct format.

**Comment by MansMeg** [comment]
Great!
